### ISSUE TITLE
Health can go negative

### ISSUE THREAD

**Issue by osmanseker** [RasitAkay11/c-SI#9]

**Comment by RasitAkay11** [comment]
Yea it does. It did. Changed te type of healt. went from int to unsigned __8 that has a range from 0 to... Healt cant go negative anymore. 
![image](https://user-images.githubusercontent.com/50198490/104128794-dd09a380-5369-11eb-8638-d4e3710e40d1.png)

![image](https://user-images.githubusercontent.com/50198490/104128803-e5fa7500-5369-11eb-9265-7f2244149f2d.png)
